# ansible-playbook -i ~/ansible/hosts /playbooks/setup-retropie-pi-cade.yml
---
- hosts: raspi
  tasks:

    - name: Copy file with owner and permissions
      copy:
        src: "{{ assistant_file }}"
        dest: /home/pi/assistant.zip
        owner: pi
        group: pi
        mode: '0644'

    - name: Clean assistant path
      become: yes
      file:
        state: absent
        path: /usr/share/snips/assistant/

    - name: Creates directory
      become: yes
      file:
        path: /usr/share/snips
        state: directory

    - name: Unarchive a file that is already on the remote machine
      become: yes
      unarchive:
        src: /home/pi/assistant.zip
        dest: /usr/share/snips/
        remote_src: yes

    - name: restart service snips
      become: yes
      systemd:
        state: restarted
        no_block: yes
        name: "{{ item }}"
      with_items:
        - snips-asr.service
        - snips-audio-server.service
        - snips-dialogue.service
        - snips-hotword.service
        - snips-nlu.service
        - snips-skill-server.service
        - snips-tts.service
