# ansible-playbook -i ~/ansible/hosts /playbooks/setup-retropie-pi-cade.yml
---
- hosts: raspicam
  tasks:

    - name: Add the user 'pi' and a primary group of 'snips-skills-admin'
      become: yes
      user:
        name: pi
        group: snips-skills-admin

    - name: Add the user '_snips-skills' and a primary group of 'spi,gpio,audio'
      user:
        name: _snips-skills
        groups: spi,gpio,audio

    - name: Clone github repository
      git:
        repo: https://github.com/snipsco/snips-skill-respeaker.git
        dest: /home/pi/snips-skill-respeaker

    - name: Move foo to bar
      become: yes
      command: cp -r snips-skill-respeaker /var/lib/snips/skills/

    - name: Launch task
      become: yes
      shell:
        cmd: ./setup.sh
        chdir: /var/lib/snips/skills/snips-skill-respeaker
